[package]
name = "muffin"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
crossterm = "0.29.0"
ratatui = "0.29.0"
regex = "1.12.2"
tokio = { version = "1.48.0", features = ["rt", "time"] }
tui-textarea = "0.7.0"
